-- ==============================================================================
-- Migration: Add user_notification_settings table for Personal Alerts
-- Run this script in Supabase SQL Editor
-- ==============================================================================

-- 1. Create table user_notification_settings
CREATE TABLE IF NOT EXISTS public.user_notification_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE NOT NULL,
    discord_webhook_url TEXT,
    alert_email TEXT,
    enable_discord BOOLEAN DEFAULT TRUE NOT NULL,
    enable_email BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Create index on user_id
CREATE INDEX IF NOT EXISTS idx_user_notification_settings_user_id 
    ON public.user_notification_settings (user_id);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.user_notification_settings ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies
DROP POLICY IF EXISTS "Users can view own notification settings" ON public.user_notification_settings;
CREATE POLICY "Users can view own notification settings" 
    ON public.user_notification_settings 
    FOR SELECT 
    TO authenticated 
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own notification settings" ON public.user_notification_settings;
CREATE POLICY "Users can insert own notification settings" 
    ON public.user_notification_settings 
    FOR INSERT 
    TO authenticated 
    WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own notification settings" ON public.user_notification_settings;
CREATE POLICY "Users can update own notification settings" 
    ON public.user_notification_settings 
    FOR UPDATE 
    TO authenticated 
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own notification settings" ON public.user_notification_settings;
CREATE POLICY "Users can delete own notification settings" 
    ON public.user_notification_settings 
    FOR DELETE 
    TO authenticated 
    USING (auth.uid() = user_id);
