-- ==============================================================================
-- Personnel Certificate Management System - Complete Master Schema (v3)
-- Includes:
--   1. personnel (บุคลากร พร้อมช่องทางแจ้งเตือนส่วนตัว และเปิด/ปิดชื่อ)
--   2. certificates (ใบประกาศนียบัตร 1 คนมีได้หลายใบ)
--   3. user_profiles (การอนุมัติผู้ใช้ และ Role Admin/Staff)
--   4. master_positions (ตำแหน่งงาน จัดการได้)
--   5. master_cert_types (ประเภทใบประกาศ จัดการได้)
-- ==============================================================================

-- 1. Table: personnel
CREATE TABLE IF NOT EXISTS public.personnel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    position TEXT,
    email TEXT,
    discord_webhook_url TEXT,
    enable_discord BOOLEAN DEFAULT TRUE NOT NULL,
    enable_email BOOLEAN DEFAULT TRUE NOT NULL,
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    note TEXT,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Table: certificates
CREATE TABLE IF NOT EXISTS public.certificates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personnel_id BIGINT REFERENCES public.personnel(id) ON DELETE CASCADE NOT NULL,
    cert_name TEXT NOT NULL,
    cert_no TEXT,
    expire_date DATE,
    status_note TEXT,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Table: user_profiles (User Approval Workflow)
CREATE TABLE IF NOT EXISTS public.user_profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    full_name TEXT,
    role TEXT DEFAULT 'staff' NOT NULL, -- 'admin' | 'staff'
    status TEXT DEFAULT 'pending' NOT NULL, -- 'pending' | 'approved' | 'rejected'
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. Table: master_positions
CREATE TABLE IF NOT EXISTS public.master_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 5. Table: master_cert_types
CREATE TABLE IF NOT EXISTS public.master_cert_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_personnel_name ON public.personnel (name);
CREATE INDEX IF NOT EXISTS idx_personnel_is_active ON public.personnel (is_active);
CREATE INDEX IF NOT EXISTS idx_certificates_personnel_id ON public.certificates (personnel_id);
CREATE INDEX IF NOT EXISTS idx_certificates_expire_date ON public.certificates (expire_date);
CREATE INDEX IF NOT EXISTS idx_user_profiles_status ON public.user_profiles (status);

-- Enable RLS
ALTER TABLE public.personnel ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.master_positions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.master_cert_types ENABLE ROW LEVEL SECURITY;

-- RLS Policies for personnel
CREATE POLICY "Allow authenticated read personnel" ON public.personnel FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated insert personnel" ON public.personnel FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow authenticated update personnel" ON public.personnel FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated delete personnel" ON public.personnel FOR DELETE TO authenticated USING (true);

-- RLS Policies for certificates
CREATE POLICY "Allow authenticated read certificates" ON public.certificates FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated insert certificates" ON public.certificates FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow authenticated update certificates" ON public.certificates FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated delete certificates" ON public.certificates FOR DELETE TO authenticated USING (true);

-- RLS Policies for user_profiles
CREATE POLICY "Users can read own profile" ON public.user_profiles FOR SELECT TO authenticated USING (auth.uid() = id);
CREATE POLICY "Admins can read all profiles" ON public.user_profiles FOR SELECT TO authenticated USING (
    EXISTS (SELECT 1 FROM public.user_profiles WHERE id = auth.uid() AND role = 'admin' AND status = 'approved')
);
CREATE POLICY "Admins can update profiles" ON public.user_profiles FOR UPDATE TO authenticated USING (
    EXISTS (SELECT 1 FROM public.user_profiles WHERE id = auth.uid() AND role = 'admin' AND status = 'approved')
);
CREATE POLICY "Admins can delete profiles" ON public.user_profiles FOR DELETE TO authenticated USING (
    EXISTS (SELECT 1 FROM public.user_profiles WHERE id = auth.uid() AND role = 'admin' AND status = 'approved')
);

-- RLS Policies for master_positions & master_cert_types
CREATE POLICY "Allow authenticated read master_positions" ON public.master_positions FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated insert master_positions" ON public.master_positions FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow authenticated update master_positions" ON public.master_positions FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated delete master_positions" ON public.master_positions FOR DELETE TO authenticated USING (true);

CREATE POLICY "Allow authenticated read master_cert_types" ON public.master_cert_types FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated insert master_cert_types" ON public.master_cert_types FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow authenticated update master_cert_types" ON public.master_cert_types FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated delete master_cert_types" ON public.master_cert_types FOR DELETE TO authenticated USING (true);

-- Trigger for new user registration
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
    is_first BOOLEAN;
    is_default_admin BOOLEAN;
BEGIN
    SELECT (COUNT(*) = 0) INTO is_first FROM public.user_profiles;
    is_default_admin := (NEW.email = 'issarapong.suya@gmail.com') OR is_first;

    INSERT INTO public.user_profiles (id, email, full_name, role, status)
    VALUES (
        NEW.id,
        NEW.email,
        COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)),
        CASE WHEN is_default_admin THEN 'admin' ELSE 'staff' END,
        CASE WHEN is_default_admin THEN 'approved' ELSE 'pending' END
    )
    ON CONFLICT (id) DO NOTHING;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Seed initial master positions
INSERT INTO public.master_positions (name) VALUES 
    ('พยาบาลวิชาชีพชำนาญการพิเศษ'),
    ('พยาบาลวิชาชีพชำนาญการ'),
    ('พยาบาลวิชาชีพปฏิบัติการ'),
    ('พยาบาลวิชาชีพ'),
    ('EMT-B (พนักงานการแพทย์ฉุกเฉิน)'),
    ('EMT-I (เจ้าพนักงานเวชกิจฉุกเฉิน)'),
    ('EMR (อาสาสมัครฉุกเฉินการแพทย์)'),
    ('เจ้าหน้าที่เวชกิจฉุกเฉิน'),
    ('พนักงานขับรถพยาบาล'),
    ('เจ้าหน้าที่กู้ชีพ')
ON CONFLICT (name) DO NOTHING;

-- Seed initial master cert types
INSERT INTO public.master_cert_types (name) VALUES 
    ('ใบอนุญาตประกอบวิชาชีพการพยาบาลและการผดุงครรภ์'),
    ('ประกาศนียบัตรผู้ปฏิบัติการแพทย์ขั้นพื้นฐาน (EMT-B)'),
    ('ประกาศนียบัตรอาสาสมัครฉุกเฉินการแพทย์ (EMR)'),
    ('ประกาศนียบัตรการช่วยฟื้นคืนชีพขั้นสูง (ACLS)'),
    ('ประกาศนียบัตรการช่วยฟื้นคืนชีพขั้นพื้นฐาน (BLS/CPR)'),
    ('ประกาศนียบัตรการดูแลผู้บาดเจ็บขั้นสูง (ITLS/PHTLS)'),
    ('ใบอนุญาตขับรถยนต์ส่วนบุคคล/รถพยาบาลฉุกเฉิน')
ON CONFLICT (name) DO NOTHING;
