-- ==============================================================================
-- Upgrade v2: 1-to-N Personnel & Certificates Schema with Personal Alerts & Active Toggle
-- Run this in Supabase SQL Editor
-- ==============================================================================

-- 1. Create table: personnel
CREATE TABLE IF NOT EXISTS public.personnel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    position TEXT,
    email TEXT,
    discord_webhook_url TEXT,
    enable_discord BOOLEAN DEFAULT TRUE NOT NULL,
    enable_email BOOLEAN DEFAULT TRUE NOT NULL,
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    note TEXT,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Create table: certificates (1 person can have multiple certificates)
CREATE TABLE IF NOT EXISTS public.certificates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personnel_id BIGINT REFERENCES public.personnel(id) ON DELETE CASCADE NOT NULL,
    cert_name TEXT NOT NULL,
    cert_no TEXT,
    expire_date DATE,
    status_note TEXT,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Create Indexes
CREATE INDEX IF NOT EXISTS idx_personnel_name ON public.personnel (name);
CREATE INDEX IF NOT EXISTS idx_personnel_is_active ON public.personnel (is_active);
CREATE INDEX IF NOT EXISTS idx_certificates_personnel_id ON public.certificates (personnel_id);
CREATE INDEX IF NOT EXISTS idx_certificates_expire_date ON public.certificates (expire_date);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.personnel ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;

-- 5. RLS Policies for personnel
DROP POLICY IF EXISTS "Allow authenticated users to read personnel" ON public.personnel;
CREATE POLICY "Allow authenticated users to read personnel" 
    ON public.personnel FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow authenticated users to insert personnel" ON public.personnel;
CREATE POLICY "Allow authenticated users to insert personnel" 
    ON public.personnel FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated users to update personnel" ON public.personnel;
CREATE POLICY "Allow authenticated users to update personnel" 
    ON public.personnel FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated users to delete personnel" ON public.personnel;
CREATE POLICY "Allow authenticated users to delete personnel" 
    ON public.personnel FOR DELETE TO authenticated USING (true);

-- 6. RLS Policies for certificates
DROP POLICY IF EXISTS "Allow authenticated users to read certificates" ON public.certificates;
CREATE POLICY "Allow authenticated users to read certificates" 
    ON public.certificates FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow authenticated users to insert certificates" ON public.certificates;
CREATE POLICY "Allow authenticated users to insert certificates" 
    ON public.certificates FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated users to update certificates" ON public.certificates;
CREATE POLICY "Allow authenticated users to update certificates" 
    ON public.certificates FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated users to delete certificates" ON public.certificates;
CREATE POLICY "Allow authenticated users to delete certificates" 
    ON public.certificates FOR DELETE TO authenticated USING (true);

-- 7. Seed Initial Data from cert_person.xlsx into the new relational tables
DO $$
DECLARE
    pid BIGINT;
BEGIN
    -- Only seed if personnel table is empty
    IF NOT EXISTS (SELECT 1 FROM public.personnel LIMIT 1) THEN

        -- 1
        INSERT INTO public.personnel (name, position, is_active) VALUES ('น.ส.สุกานดา สุภาจันทร์', 'พยาบาลวิชาชีพชำนาญการพิเศษ', true) RETURNING id INTO pid;
        INSERT INTO public.certificates (personnel_id, cert_name, expire_date, status_note) VALUES (pid, 'ใบอนุญาตประกอบวิชาชีพการพยาบาล', '2027-12-23', NULL);

        -- 2
        INSERT INTO public.personnel (name, position, is_active) VALUES ('นางนาตยา ทาริน', 'พยาบาลวิชาชีพชำนาญการ', true) RETURNING id INTO pid;
        INSERT INTO public.certificates (personnel_id, cert_name, expire_date, status_note) VALUES (pid, 'ใบอนุญาตประกอบวิชาชีพการพยาบาล', '2027-07-28', NULL);

        -- 3
        INSERT INTO public.personnel (name, position, is_active) VALUES ('น.ส.สมฤทัย ใหม่คามิ', 'พยาบาลวิชาชีพชำนาญการ', true) RETURNING id INTO pid;
        INSERT INTO public.certificates (personnel_id, cert_name, expire_date, status_note) VALUES (pid, 'ใบอนุญาตประกอบวิชาชีพการพยาบาล', '2030-03-20', NULL);

        -- 4
        INSERT INTO public.personnel (name, position, is_active) VALUES ('นางเสาวลักษณ์ ยานะ', 'พยาบาลวิชาชีพชำนาญการ', true) RETURNING id INTO pid;
        INSERT INTO public.certificates (personnel_id, cert_name, expire_date, status_note) VALUES (pid, 'ใบอนุญาตประกอบวิชาชีพการพยาบาล', '2031-03-19', NULL);

        -- 5
        INSERT INTO public.personnel (name, position, is_active) VALUES ('น.ส.สุนิตา คำวงษา', 'พยาบาลวิชาชีพปฏิบัติการ', true) RETURNING id INTO pid;
        INSERT INTO public.certificates (personnel_id, cert_name, expire_date, status_note) VALUES (pid, 'ใบอนุญาตประกอบวิชาชีพการพยาบาล', '2030-07-19', NULL);

        -- 6
        INSERT INTO public.personnel (name, position, is_active) VALUES ('น.ส.ฐิตาพร พนมไพศาลสกุล', 'พยาบาลวิชาชีพปฏิบัติการ', true) RETURNING id INTO pid;
        INSERT INTO public.certificates (personnel_id, cert_name, expire_date, status_note) VALUES (pid, 'ใบอนุญาตประกอบวิชาชีพการพยาบาล', '2028-03-18', NULL);

        -- 7
        INSERT INTO public.personnel (name, position, is_active) VALUES ('น.ส.เบญจมาศ เหลี่ยมแหลม', 'พยาบาลวิชาชีพปฏิบัติการ', true) RETURNING id INTO pid;
        INSERT INTO public.certificates (personnel_id, cert_name, expire_date, status_note) VALUES (pid, 'ใบอนุญาตประกอบวิชาชีพการพยาบาล', '2028-03-26', 'เตือนก่อนหมดอายุ 7 วัน');

        -- 8
        INSERT INTO public.personnel (name, position, is_active) VALUES ('น.ส.เกสราพรรณ คำแสน', 'พยาบาลวิชาชีพ', true) RETURNING id INTO pid;
        INSERT INTO public.certificates (personnel_id, cert_name, expire_date, status_note) VALUES (pid, 'ใบอนุญาตประกอบวิชาชีพการพยาบาล', '2029-03-24', 'เตือนก่อนหมดอายุ 1 วัน');

        -- 9
        INSERT INTO public.personnel (name, position, is_active) VALUES ('น.ส.วรินดา ณ คำมูล', 'พยาบาลวิชาชีพ', true) RETURNING id INTO pid;
        INSERT INTO public.certificates (personnel_id, cert_name, expire_date, status_note) VALUES (pid, 'ใบอนุญาตประกอบวิชาชีพการพยาบาล', '2029-03-24', 'เตือนก่อนหมดอายุ 90 วัน');

        -- 10
        INSERT INTO public.personnel (name, position, is_active) VALUES ('น.ส.ภัทรินทร์ กิ่งแก้ว', 'พยาบาลวิชาชีพ', true) RETURNING id INTO pid;
        INSERT INTO public.certificates (personnel_id, cert_name, expire_date, status_note) VALUES (pid, 'ใบอนุญาตประกอบวิชาชีพการพยาบาล', '2029-03-24', NULL);

        -- 11
        INSERT INTO public.personnel (name, position, is_active) VALUES ('น.ส.ฐิตยา ยิ่งตะกูล', 'พยาบาลวิชาชีพ', true) RETURNING id INTO pid;
        INSERT INTO public.certificates (personnel_id, cert_name, expire_date, status_note) VALUES (pid, 'ใบอนุญาตประกอบวิชาชีพการพยาบาล', '2029-03-24', NULL);

        -- 12
        INSERT INTO public.personnel (name, position, is_active) VALUES ('นายศตวรรษ พรมวัง', 'EMT-B', true) RETURNING id INTO pid;
        INSERT INTO public.certificates (personnel_id, cert_name, expire_date, status_note) VALUES (pid, 'ประกาศนียบัตรผู้ปฏิบัติการแพทย์ขั้นพื้นฐาน (EMT-B)', NULL, 'รอต่อ EMT-B');

        -- 13
        INSERT INTO public.personnel (name, position, is_active) VALUES ('นายต่อตระกูล สุขมอย', 'EMT-B', true) RETURNING id INTO pid;
        INSERT INTO public.certificates (personnel_id, cert_name, expire_date, status_note) VALUES (pid, 'ประกาศนียบัตรผู้ปฏิบัติการแพทย์ขั้นพื้นฐาน (EMT-B)', '2025-03-10', NULL);

        -- 14
        INSERT INTO public.personnel (name, position, is_active) VALUES ('นายวัชริศ มหาวัน', 'EMT-B', true) RETURNING id INTO pid;
        INSERT INTO public.certificates (personnel_id, cert_name, expire_date, status_note) VALUES (pid, 'ประกาศนียบัตรผู้ปฏิบัติการแพทย์ขั้นพื้นฐาน (EMT-B)', '2025-11-10', NULL);

        -- 15
        INSERT INTO public.personnel (name, position, is_active) VALUES ('นายศุภวิชญ์ ชุ่มคำมูล', 'EMR', true) RETURNING id INTO pid;
        INSERT INTO public.certificates (personnel_id, cert_name, expire_date, status_note) VALUES (pid, 'ประกาศนียบัตรอาสาสมัครฉุกเฉินการแพทย์ (EMR)', NULL, 'รออบรม EMR');

        -- 16
        INSERT INTO public.personnel (name, position, is_active) VALUES ('นายเรืองศักดิ์ ศรีวรกุลวงศ์', 'EMR', true) RETURNING id INTO pid;
        INSERT INTO public.certificates (personnel_id, cert_name, expire_date, status_note) VALUES (pid, 'ประกาศนียบัตรอาสาสมัครฉุกเฉินการแพทย์ (EMR)', NULL, 'รอต่อ EMR');

        -- 17
        INSERT INTO public.personnel (name, position, is_active) VALUES ('นายไมตรี เครือแก้ว', 'EMT-B', true) RETURNING id INTO pid;
        INSERT INTO public.certificates (personnel_id, cert_name, expire_date, status_note) VALUES (pid, 'ประกาศนียบัตรผู้ปฏิบัติการแพทย์ขั้นพื้นฐาน (EMT-B)', '2037-03-10', NULL);

        -- 18
        INSERT INTO public.personnel (name, position, is_active) VALUES ('นายสมชาย อุตวรรณา', 'EMR', true) RETURNING id INTO pid;
        INSERT INTO public.certificates (personnel_id, cert_name, expire_date, status_note) VALUES (pid, 'ประกาศนียบัตรอาสาสมัครฉุกเฉินการแพทย์ (EMR)', '2027-03-11', NULL);

        -- 19
        INSERT INTO public.personnel (name, position, is_active) VALUES ('นายจตุพร บุญเรือง', 'EMT-B', true) RETURNING id INTO pid;
        INSERT INTO public.certificates (personnel_id, cert_name, expire_date, status_note) VALUES (pid, 'ประกาศนียบัตรผู้ปฏิบัติการแพทย์ขั้นพื้นฐาน (EMT-B)', NULL, 'รอต่อ EMT-B');

        -- 20
        INSERT INTO public.personnel (name, position, is_active) VALUES ('นายวัลลภ โพธิ์ทองคำ', 'EMT-B', true) RETURNING id INTO pid;
        INSERT INTO public.certificates (personnel_id, cert_name, expire_date, status_note) VALUES (pid, 'ประกาศนียบัตรผู้ปฏิบัติการแพทย์ขั้นพื้นฐาน (EMT-B)', NULL, 'อบรมแล้วยังไม่ได้ใบประกาศ');

        -- 21
        INSERT INTO public.personnel (name, position, is_active) VALUES ('นายวุฒิชัย ใจวงศ์คำ', 'EMT-B', true) RETURNING id INTO pid;
        INSERT INTO public.certificates (personnel_id, cert_name, expire_date, status_note) VALUES (pid, 'ประกาศนียบัตรอาสาสมัครฉุกเฉินการแพทย์ (EMR)', NULL, 'รออบรม EMR');

    END IF;
END $$;
