-- ==============================================================================
-- Upgrade v3: User Approval Workflow, Role Management, and Master Data
-- Run this in Supabase SQL Editor
-- ==============================================================================

-- 1. Create table: user_profiles
CREATE TABLE IF NOT EXISTS public.user_profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    full_name TEXT,
    role TEXT DEFAULT 'staff' NOT NULL, -- 'admin' | 'staff'
    status TEXT DEFAULT 'pending' NOT NULL, -- 'pending' | 'approved' | 'rejected'
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_user_profiles_status ON public.user_profiles (status);
CREATE INDEX IF NOT EXISTS idx_user_profiles_role ON public.user_profiles (role);

ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read own profile" ON public.user_profiles;
CREATE POLICY "Users can read own profile" 
    ON public.user_profiles FOR SELECT 
    TO authenticated 
    USING (auth.uid() = id);

DROP POLICY IF EXISTS "Admins can read all profiles" ON public.user_profiles;
CREATE POLICY "Admins can read all profiles" 
    ON public.user_profiles FOR SELECT 
    TO authenticated 
    USING (
        EXISTS (
            SELECT 1 FROM public.user_profiles 
            WHERE id = auth.uid() AND role = 'admin' AND status = 'approved'
        )
    );

DROP POLICY IF EXISTS "Admins can update profiles" ON public.user_profiles;
CREATE POLICY "Admins can update profiles" 
    ON public.user_profiles FOR UPDATE 
    TO authenticated 
    USING (
        EXISTS (
            SELECT 1 FROM public.user_profiles 
            WHERE id = auth.uid() AND role = 'admin' AND status = 'approved'
        )
    );

DROP POLICY IF EXISTS "Admins can delete profiles" ON public.user_profiles;
CREATE POLICY "Admins can delete profiles" 
    ON public.user_profiles FOR DELETE 
    TO authenticated 
    USING (
        EXISTS (
            SELECT 1 FROM public.user_profiles 
            WHERE id = auth.uid() AND role = 'admin' AND status = 'approved'
        )
    );

-- 2. Trigger function to automatically create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
    is_first BOOLEAN;
    is_default_admin BOOLEAN;
BEGIN
    -- Check if this is the first user or matches designated admin email
    SELECT (COUNT(*) = 0) INTO is_first FROM public.user_profiles;
    is_default_admin := (NEW.email = 'issarapong.suya@gmail.com') OR is_first;

    INSERT INTO public.user_profiles (id, email, full_name, role, status)
    VALUES (
        NEW.id,
        NEW.email,
        COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)),
        CASE WHEN is_default_admin THEN 'admin' ELSE 'staff' END,
        CASE WHEN is_default_admin THEN 'approved' ELSE 'pending' END
    )
    ON CONFLICT (id) DO NOTHING;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Attach trigger to auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Backfill any existing users in auth.users into user_profiles
INSERT INTO public.user_profiles (id, email, full_name, role, status)
SELECT 
    id, 
    email, 
    COALESCE(raw_user_meta_data->>'full_name', split_part(email, '@', 1)),
    CASE WHEN email = 'issarapong.suya@gmail.com' THEN 'admin' ELSE 'staff' END,
    'approved' -- Existing users before migration approved by default
FROM auth.users
ON CONFLICT (id) DO UPDATE SET 
    role = CASE WHEN EXCLUDED.email = 'issarapong.suya@gmail.com' THEN 'admin' ELSE user_profiles.role END,
    status = 'approved';

-- 3. Create table: master_positions (ตำแหน่งที่สามารถเพิ่ม/แก้ไขได้)
CREATE TABLE IF NOT EXISTS public.master_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.master_positions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow authenticated users to read master_positions" ON public.master_positions;
CREATE POLICY "Allow authenticated users to read master_positions" 
    ON public.master_positions FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow authenticated users to insert master_positions" ON public.master_positions;
CREATE POLICY "Allow authenticated users to insert master_positions" 
    ON public.master_positions FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated users to update master_positions" ON public.master_positions;
CREATE POLICY "Allow authenticated users to update master_positions" 
    ON public.master_positions FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated users to delete master_positions" ON public.master_positions;
CREATE POLICY "Allow authenticated users to delete master_positions" 
    ON public.master_positions FOR DELETE TO authenticated USING (true);

-- 4. Create table: master_cert_types (ประเภทใบประกาศนียบัตรที่สามารถเพิ่ม/แก้ไขได้)
CREATE TABLE IF NOT EXISTS public.master_cert_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.master_cert_types ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow authenticated users to read master_cert_types" ON public.master_cert_types;
CREATE POLICY "Allow authenticated users to read master_cert_types" 
    ON public.master_cert_types FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow authenticated users to insert master_cert_types" ON public.master_cert_types;
CREATE POLICY "Allow authenticated users to insert master_cert_types" 
    ON public.master_cert_types FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated users to update master_cert_types" ON public.master_cert_types;
CREATE POLICY "Allow authenticated users to update master_cert_types" 
    ON public.master_cert_types FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated users to delete master_cert_types" ON public.master_cert_types;
CREATE POLICY "Allow authenticated users to delete master_cert_types" 
    ON public.master_cert_types FOR DELETE TO authenticated USING (true);

-- 5. Seed initial data for Master Positions
INSERT INTO public.master_positions (name)
VALUES 
    ('พยาบาลวิชาชีพชำนาญการพิเศษ'),
    ('พยาบาลวิชาชีพชำนาญการ'),
    ('พยาบาลวิชาชีพปฏิบัติการ'),
    ('พยาบาลวิชาชีพ'),
    ('EMT-B (พนักงานการแพทย์ฉุกเฉิน)'),
    ('EMT-I (เจ้าพนักงานเวชกิจฉุกเฉิน)'),
    ('EMR (อาสาสมัครฉุกเฉินการแพทย์)'),
    ('เจ้าหน้าที่เวชกิจฉุกเฉิน'),
    ('พนักงานขับรถพยาบาล'),
    ('เจ้าหน้าที่กู้ชีพ')
ON CONFLICT (name) DO NOTHING;

-- 6. Seed initial data for Master Certificate Types
INSERT INTO public.master_cert_types (name)
VALUES 
    ('ใบอนุญาตประกอบวิชาชีพการพยาบาลและการผดุงครรภ์'),
    ('ประกาศนียบัตรผู้ปฏิบัติการแพทย์ขั้นพื้นฐาน (EMT-B)'),
    ('ประกาศนียบัตรอาสาสมัครฉุกเฉินการแพทย์ (EMR)'),
    ('ประกาศนียบัตรการช่วยฟื้นคืนชีพขั้นสูง (ACLS)'),
    ('ประกาศนียบัตรการช่วยฟื้นคืนชีพขั้นพื้นฐาน (BLS/CPR)'),
    ('ประกาศนียบัตรการดูแลผู้บาดเจ็บขั้นสูง (ITLS/PHTLS)'),
    ('ใบอนุญาตขับรถยนต์ส่วนบุคคล/รถพยาบาลฉุกเฉิน')
ON CONFLICT (name) DO NOTHING;
